name: passcode_biometric_auth
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/lamnhan066/passcode_biometric_auth

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  local_auth: ^2.2.0
  pinput: ^4.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
